services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data   
    environment:
      - GIN_MODE=release
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
